#include <iostream>
#include <string>

// Declaration for the function generated by Flex in lexer.cpp.
extern int yylex();
extern char* yytext;

void sampleLexer() {
    std::cout
        << "Enter source code, then press Ctrl+D on an empty line to finish:\n"
        << "> "
        << std::flush;
    int token = 0;

    while ((token = yylex()) != 0) {
        std::cout
            << "token: " << token
            << ", text: \"" << yytext << "\"\n";
    }
}

int main() {
    sampleLexer();
    return 0;
}
